import type { Config } from 'tailwindcss'
import { nextui } from '@nextui-org/theme'
import typography from '@tailwindcss/typography'
import colors from 'tailwindcss/colors'
import defaultTheme from 'tailwindcss/defaultTheme'
import tailwindAnimated from 'tailwindcss-animated'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@nextui-org/theme/dist/components/avatar.js',
    './node_modules/@nextui-org/theme/dist/components/card.js',
    './node_modules/@nextui-org/theme/dist/components/chip.js',
    './node_modules/@nextui-org/theme/dist/components/dropdown.js',
    './node_modules/@nextui-org/theme/dist/components/input.js',
    './node_modules/@nextui-org/theme/dist/components/kbd.js',
    './node_modules/@nextui-org/theme/dist/components/link.js',
    './node_modules/@nextui-org/theme/dist/components/navbar.js',
    './node_modules/@nextui-org/theme/dist/components/pagination.js',
    './node_modules/@nextui-org/theme/dist/components/popover.js',
    './node_modules/@nextui-org/theme/dist/components/radio.js',
    './node_modules/@nextui-org/theme/dist/components/select.js',
    './node_modules/@nextui-org/theme/dist/components/scroll-shadow.js',
    './node_modules/@nextui-org/theme/dist/components/switch.js',
    './node_modules/@nextui-org/theme/dist/components/tooltip.js',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        'DEFAULT': '1rem',
        'sm': '2rem',
        'lg': '4rem',
        'xl': '5rem',
        '2xl': '6rem',
      },
    },
    extend: {
      colors: {
        gray: colors.neutral,
        palettes: {
          primary: {
            0: '#000000',
            5: '#001418',
            10: '#001F25',
            15: '#002A31',
            20: '#00363E',
            25: '#00424C',
            30: '#004E5A',
            35: '#005B68',
            40: '#006877',
            50: '#008395',
            60: '#259EB2',
            70: '#4BB9CD',
            80: '#6BD5EA',
            90: '#A2EEFF',
            95: '#D4F7FF',
            98: '#EFFCFF',
            99: '#F7FDFF',
            100: '#FFFFFF',
          },
          secondary: {
            0: '#000000',
            5: '#2C000A',
            10: '#400013',
            15: '#53001B',
            20: '#670023',
            25: '#7B002C',
            30: '#910035',
            35: '#A6003E',
            40: '#BD0047',
            50: '#EB015B',
            60: '#FF4E78',
            70: '#FF869B',
            80: '#FFB2BC',
            90: '#FFD9DD',
            95: '#FFECED',
            98: '#FFF8F7',
            99: '#FFFBFF',
            100: '#FFFFFF',
          },
        },
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', ...defaultTheme.fontFamily.sans],
        mono: ['var(--font-geist-mono)', ...defaultTheme.fontFamily.mono],
      },
      typography: () => ({
        quoteless: {
          css: {
            'blockquote p:first-of-type::before': { content: 'none' },
            'blockquote p:first-of-type::after': { content: 'none' },
          },
        },
        custom: {
          css: {
            '--tw-prose-body': 'var(--color-body)',
            '--tw-prose-headings': 'var(--color-headings)',
            '--tw-prose-lead': 'var(--color-lead)',
            '--tw-prose-links': 'var(--color-links)',
            '--tw-prose-bold': 'var(--color-bold)',
            '--tw-prose-counters': 'var(--color-counters)',
            '--tw-prose-bullets': 'var(--color-bullets)',
            '--tw-prose-hr': 'var(--color-hr)',
            '--tw-prose-quotes': 'var(--color-quotes)',
            '--tw-prose-quote-borders': 'var(--color-quote-borders)',
            '--tw-prose-captions': 'var(--color-captions)',
            '--tw-prose-code': 'var(--color-code-fg)',
            '--tw-prose-pre-bg': 'var(--color-pre-code-bg)',
            '--tw-prose-pre-code': 'var(--color-pre-code-fg)',
            '--tw-prose-th-borders': 'var(--color-th-borders)',
            '--tw-prose-td-borders': 'var(--color-td-borders)',
          },
        },
      }),
    },
  },
  plugins: [
    typography,
    tailwindAnimated,
    nextui({
      prefix: 'nextui',
      defaultExtendTheme: 'light',
      themes: {
        light: {
          colors: {
            default: {
              50: '#ffffff',
              100: '#fafafa',
              200: '#f5f5f5',
              300: '#e5e5e5',
              400: '#d4d4d4',
              500: '#a3a3a3',
              600: '#737373',
              700: '#525252',
              800: '#404040',
              900: '#262626',
            },
            content1: '#ffffff',
            content2: '#fafafa',
            content3: '#f5f5f5',
            content4: '#e5e5e5',
            background: '#fafafa',
            foreground: '#404040',
            primary: {
              50: '#ecfeff',
              100: '#cffafe',
              200: '#a5f3fc',
              300: '#67e8f9',
              400: '#22d3ee',
              500: '#06b6d4',
              600: '#0891b2',
              700: '#0e7490',
              800: '#155e75',
              900: '#164e63',
              foreground: '#ffffff',
              DEFAULT: '#0e7490',
            },
            secondary: {
              50: '#fef2f2',
              100: '#fee2e2',
              200: '#fecaca',
              300: '#fca5a5',
              400: '#f87171',
              500: '#ef4444',
              600: '#dc2626',
              700: '#b91c1c',
              800: '#991b1b',
              900: '#7f1d1d',
              foreground: '#ffffff',
              DEFAULT: '#b91c1c',
            },
            divider: 'rgba(17, 17, 17, 0.15)',
            focus: '#006877',
          },
        },
        dark: {
          colors: {
            default: {
              50: '#262626',
              100: '#404040',
              200: '#525252',
              300: '#737373',
              400: '#a3a3a3',
              500: '#d4d4d4',
              600: '#e5e5e5',
              700: '#f5f5f5',
              800: '#fafafa',
              900: '#ffffff',
            },
            content1: '#262626',
            content2: '#404040',
            content3: '#525252',
            content4: '#737373',
            background: '#0a0a0a',
            foreground: '#fafafa',
            primary: {
              50: '#164e63',
              100: '#155e75',
              200: '#0e7490',
              300: '#0891b2',
              400: '#06b6d4',
              500: '#22d3ee',
              600: '#67e8f9',
              700: '#a5f3fc',
              800: '#cffafe',
              900: '#ecfeff',
              foreground: '#164e63',
              DEFAULT: '#a5f3fc',
            },
            secondary: {
              50: '#7f1d1d',
              100: '#991b1b',
              200: '#b91c1c',
              300: '#dc2626',
              400: '#ef4444',
              500: '#f87171',
              600: '#fca5a5',
              700: '#fecaca',
              800: '#fee2e2',
              900: '#fef2f2',
              foreground: '#7f1d1d',
              DEFAULT: '#fecaca',
            },
            divider: 'rgba(255, 255, 255, 0.15)',
            focus: '#00363E',
          },
        },
      },
    }),
  ],
}
export default config
